#!/usr/bin/env node
/**
 * Vendor sync: refresh `vendor/` from a DeepSeek Harness checkout.
 *
 * The standalone pet vendors the prebuilt artifacts of
 * `@deepseek-ai/dsh-sdk-client` and `@deepseek-ai/dsh-sdk-protocol` so it
 * builds without the monorepo. This script copies them from a checkout and
 * rewrites their external `@deepseek-ai/*` imports to relative paths, then
 * regenerates the small type-stub packages (`dsh-llm`, `dsh-session`,
 * `dsh-subagent`) the vendored `.d.ts` files reference.
 *
 * Usage:
 *   node scripts/sync-vendor.mjs                # DSH_REPO env or ./../deepseek-harness
 *   node scripts/sync-vendor.mjs E:\repo        # explicit checkout path
 *   node scripts/sync-vendor.mjs --check        # verify vendored files match a refresh
 *
 * The copied artifacts come from the same `deepseek-harness` repository this
 * project was extracted from; see vendor/README.md for provenance.
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const vendor = join(root, 'vendor')

const CHECK = process.argv.includes('--check')
const repoArg = process.argv.find((arg, index) => index > 1 && arg !== '--check')
const repo = repoArg ?? process.env.DSH_REPO ?? join(root, '..', 'deepseek-harness')

const clientSrc = join(repo, 'packages', 'sdk', 'client')
const protocolSrc = join(repo, 'packages', 'sdk', 'protocol')

function die(message) {
  console.error(`sync-vendor: ${message}`)
  process.exit(1)
}

if (!existsSync(join(clientSrc, 'lib', 'index.js'))) die(`cannot find sdk client build at ${clientSrc} (build the checkout first)`)
if (!existsSync(join(protocolSrc, 'lib', 'index.js'))) die(`cannot find sdk protocol build at ${protocolSrc}`)

/** Apply the deterministic import rewrites to one text file. */
function rewrite(text, rules) {
  let out = text
  for (const [pattern, replacement] of rules) out = out.replace(pattern, replacement)
  return out
}

const REWRITES = {
  'dsh-sdk-client/index.js': [
    [/from "@deepseek-ai\/dsh-sdk-protocol"/g, 'from "../dsh-sdk-protocol/index.js"'],
  ],
  'dsh-sdk-client/types/*.d.ts': [
    [/from '@deepseek-ai\/dsh-sdk-protocol'/g, "from '../../dsh-sdk-protocol/index.js'"],
    [/from '@deepseek-ai\/dsh-llm'/g, "from '../../dsh-llm/index.js'"],
    [/from '@deepseek-ai\/dsh-session'/g, "from '../../dsh-session/index.js'"],
    [/from '\.\/types\.ts'/g, "from './types.js'"],
    [/from '\.\/api\.ts'/g, "from './api.js'"],
    [/from '\.\/client\.ts'/g, "from './client.js'"],
    [/from '\.\/dispose\.ts'/g, "from './dispose.js'"],
    [/from '\.\/index\.ts'/g, "from './index.js'"],
  ],
  'dsh-sdk-protocol/types/*.d.ts': [
    [/from '@deepseek-ai\/dsh-llm'/g, "from '../../dsh-llm/index.js'"],
    [/from '@deepseek-ai\/dsh-session'/g, "from '../../dsh-session/index.js'"],
    [/from '@deepseek-ai\/dsh-subagent'/g, "from '../../dsh-subagent/index.js'"],
    [/from '\.\/types\.ts'/g, "from './types.js'"],
    [/from '\.\/transport\.ts'/g, "from './transport.js'"],
  ],
}

const BARREL = "export * from './types/index.js'\n"

/** Hand-maintained type stubs, embedded so a full refresh is self-contained. */
const STUBS = {
  'dsh-llm/index.d.ts': `/**
 * Minimal structural type stub for \`@deepseek-ai/dsh-llm\`, vendored so the
 * SDK client's declaration files compile without the monorepo package.
 * Generated by \`scripts/sync-vendor.mjs\`; refresh with \`npm run sync-vendor\`.
 */

/** One content block in an assistant/user message, as the pet consumes it. */
export type ContentBlock =
  | { type: 'text'; text: string }
  | { type: 'thinking'; text: string; signature?: string }
  | { type: 'image'; imageUrl?: string; image?: unknown; alt?: string }
  | { type: 'tool'; toolCallId?: string; name?: string; arguments?: unknown; isError?: boolean; content?: unknown }
  | { type: 'refusal'; refusal?: string }
  | Record<string, unknown>
`,
  'dsh-session/index.d.ts': `/**
 * Minimal structural type stub for \`@deepseek-ai/dsh-session\`, vendored so
 * the SDK client's declaration files compile without the monorepo package.
 * Generated by \`scripts/sync-vendor.mjs\`; refresh with \`npm run sync-vendor\`.
 */

/** One merge-extensible session-log event envelope. */
export interface SessionEvent {
  type: string
  data?: Record<string, unknown>
  turn?: number
  [key: string]: unknown
}
`,
  'dsh-subagent/index.d.ts': `/**
 * Minimal structural type stub for \`@deepseek-ai/dsh-subagent\`, vendored so
 * the SDK client's declaration files compile without the monorepo package.
 * Generated by \`scripts/sync-vendor.mjs\`; refresh with \`npm run sync-vendor\`.
 */

/** Deployment-mapped provider stop reason for a subagent run. */
export type SubagentStopReason = 'complete' | 'error' | 'cancelled' | 'length' | string
`,
}

/** Compute the expected content of every vendored file. */
async function expectedFiles() {
  const files = new Map()

  // SDK client bundle + declarations (skip invariant and source maps).
  files.set('dsh-sdk-client/index.js', rewrite(await readFile(join(clientSrc, 'lib', 'index.js'), 'utf8'), REWRITES['dsh-sdk-client/index.js']))
  files.set('dsh-sdk-client/index.d.ts', BARREL)
  for (const name of await readdir(join(clientSrc, 'lib', 'types'))) {
    if (!name.endsWith('.d.ts') || name === 'invariant.d.ts') continue
    files.set(`dsh-sdk-client/types/${name}`, rewrite(await readFile(join(clientSrc, 'lib', 'types', name), 'utf8'), REWRITES['dsh-sdk-client/types/*.d.ts']))
  }

  // SDK protocol bundle + declarations.
  files.set('dsh-sdk-protocol/index.js', await readFile(join(protocolSrc, 'lib', 'index.js'), 'utf8'))
  files.set('dsh-sdk-protocol/index.d.ts', BARREL)
  for (const name of await readdir(join(protocolSrc, 'lib', 'types'))) {
    if (!name.endsWith('.d.ts') || name === 'invariant.d.ts') continue
    files.set(`dsh-sdk-protocol/types/${name}`, rewrite(await readFile(join(protocolSrc, 'lib', 'types', name), 'utf8'), REWRITES['dsh-sdk-protocol/types/*.d.ts']))
  }

  // Type stubs.
  for (const [relative, content] of Object.entries(STUBS)) files.set(relative, content)
  return files
}

async function main() {
  if (CHECK) {
    const expected = await expectedFiles()
    let mismatch = false
    for (const [relative, content] of expected) {
      const path = join(vendor, relative)
      if (!existsSync(path)) {
        console.error(`missing: vendor/${relative}`)
        mismatch = true
        continue
      }
      const actual = await readFile(path, 'utf8')
      if (actual !== content) {
        console.error(`out of date: vendor/${relative} (run sync-vendor.mjs)`)
        mismatch = true
      }
    }
    if (mismatch) {
      console.error('sync-vendor: vendored files are out of date')
      process.exit(1)
    }
    console.log('sync-vendor: vendored files are up to date')
    return
  }

  // Only the managed package dirs are regenerated; vendor/README.md survives.
  for (const dir of ['dsh-sdk-client', 'dsh-sdk-protocol', 'dsh-llm', 'dsh-session', 'dsh-subagent']) {
    await rm(join(vendor, dir), { recursive: true, force: true })
  }
  await mkdir(vendor, { recursive: true })
  const expected = await expectedFiles()
  for (const [relative, content] of expected) {
    const path = join(vendor, relative)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, content, 'utf8')
  }
  console.log(`sync-vendor: refreshed vendor/ from ${repo}`)
}

await main()
